# Generated by Django 5.2.3 on 2025-06-27 01:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GitHub Token'),
        ),

    ]
