# Generated by Django 5.2.1 on 2025-06-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
