# Generated by Django 5.2.3 on 2025-06-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Image'),
        ),
    ]
