# Generated by Django 5.2.3 on 2025-06-30 04:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_updated_at_user_profile_image_scantask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('analyst', 'Analyst'), ('customer_manager', 'Customer Manager'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
    ]
