# config/tasks.yaml
# ────────────────────────────────────────────
db_query:

  description: >
    ### Available Tables
    Table: telecom_customers(customer_id, gender, senior_citizen, partner, dependents, tenure, phone_service, multiple_lines, internet_service, online_security, online_backup, device_protection, tech_support, streaming_tv, streaming_movies, contract, paperless_billing, payment_method, monthly_charges, total_charges) # 이탈 여부는 조회하지않도록해
    Table: summary_news_keywords(id, date, keyword, title, summary, url)
    Table: analytics_results(id, result_type, s3_key, meta, created_at, user_id)
    Table: chat_messages(id, role, content, created_at, session_id, metadata)
    Table: chat_sessions(id, agent_type, started_at, ended_at, user_id, title)
    Table: llm_calls(id, call_type, prompt, response, tokens_used, latency_ms, created_at, user_id, session_id)
    Table: model_artifacts(id, artifact_type, s3_key, meta, created_at, user_id)
    Table: organizations(id, name, created_at)
    Table: users(id, email, hashed_password, full_name, created_at, updated_at, is_active, is_staff, org_id)

    Convert the user's question "{query}" into appropriate SQL and execute it.
    Your final output MUST be a JSON string with two keys:
    1. "original_query": This MUST be the exact user question you received, which is "{query}".
    2. "sql_result": This MUST be the SQL execution results, preferably in a CSV-like string format.

  expected_output: >
    A JSON string containing "original_query" and "sql_result".
    Example: {{"original_query": "show me sales data for last month", "sql_result": "product,revenue\napples,1200\noranges,800"}}
  agent: db_analyst          # ← Worker designation

data_viz:
  description: >
    1) Input table from which the most appropriate chart (pie, bar, etc.) is generated.
    2) Generate a self-contained HTML/JavaScript snippet for the chart using Chart.js.
    3) Summarize the key insights of the data.
  expected_output: >
    JSON object {"chart_html": "<html_snippet>", "summary": "..."} form
  agent: viz_analyst