# Generated by Django 5.2.1 on 2025-06-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('thread_id', models.TextField(primary_key=True, serialize=False)),
                ('checkpoint_ns', models.TextField(default='')),
                ('checkpoint_id', models.TextField()),
                ('parent_checkpoint_id', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('checkpoint', models.JSONField()),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'checkpoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckpointBlob',
            fields=[
                ('thread_id', models.TextField(primary_key=True, serialize=False)),
                ('checkpoint_ns', models.TextField(default='')),
                ('channel', models.TextField()),
                ('version', models.TextField()),
                ('type', models.TextField()),
                ('blob', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'checkpoint_blobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckpointMigration',
            fields=[
                ('v', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'checkpoint_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckpointWrite',
            fields=[
                ('thread_id', models.TextField(primary_key=True, serialize=False)),
                ('checkpoint_ns', models.TextField(default='')),
                ('checkpoint_id', models.TextField()),
                ('task_id', models.TextField()),
                ('idx', models.IntegerField()),
                ('channel', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('blob', models.BinaryField()),
            ],
            options={
                'db_table': 'checkpoint_writes',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='새 세션', max_length=60),
        ),
    ]
