# Generated by Django 5.2.1 on 2025-06-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_checkpoint_checkpointblob_checkpointmigration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkpoint',
        ),
        migrations.DeleteModel(
            name='CheckpointBlob',
        ),
        migrations.DeleteModel(
            name='CheckpointMigration',
        ),
        migrations.DeleteModel(
            name='CheckpointWrite',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='agent_type',
            field=models.CharField(choices=[('code', 'Code'), ('rag', 'RAG'), ('analytics', 'Analytics'), ('auto', 'Auto')], max_length=20),
        ),
    ]
