# Generated by Django 5.2.3 on 2025-06-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_delete_checkpoint_delete_checkpointblob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='thread_id',
            field=models.UUIDField(blank=True, help_text='LangGraph thread ID', null=True),
        ),
    ]
