# Generated by Django 5.2.3 on 2025-06-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_chatsession_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='tool_data',
            field=models.JSONField(blank=True, help_text='Tool calls and outputs data', null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='agent_type',
            field=models.CharField(choices=[('code', 'Code'), ('rag', 'RAG'), ('analytics', 'Analytics'), ('auto', 'Auto'), ('default', 'Default')], max_length=20),
        ),
    ]
