# Generated by Django 5.2.3 on 2025-06-21 10:59

import conversations.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_chatmessage_tool_data_alter_chatsession_agent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=conversations.models.get_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='conversations.chatmessage')),
            ],
            options={
                'db_table': 'message_files',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
