# Generated by Django 5.2.3 on 2025-06-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_chatmessage_tool_data_alter_chatsession_agent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='deleted_check',
            field=models.BooleanField(default=False),
        ),
    ]
