# Generated by Django 5.2.3 on 2025-06-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_chatsession_deleted_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_content',
            field=models.TextField(blank=True, help_text='Base64 encoded file content or file path', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
