# Generated by Django 5.2.1 on 2025-05-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summarynewskeywords',
            options={'verbose_name_plural': 'Summary news keywords'},
        ),
        migrations.AlterModelOptions(
            name='telecomcustomers',
            options={'verbose_name_plural': 'Telecom customers'},
        ),
        migrations.RemoveIndex(
            model_name='summarynewskeywords',
            name='idx_news_date',
        ),
        migrations.RemoveIndex(
            model_name='summarynewskeywords',
            name='idx_news_keyword',
        ),
    ]
