# Generated by Django 5.2.1 on 2025-05-29 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('churn_pred', 'Churn Prediction'), ('viz_image', 'Visualization Image'), ('timeseries_forecast', 'Time-series Forecast')], max_length=30)),
                ('s3_key', models.TextField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_results',
                'indexes': [models.Index(fields=['user', 'result_type'], name='idx_analytics_user_type')],
            },
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(default='v1', max_length=50)),
                ('s3_key', models.TextField()),
                ('stage', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production'), ('archived', 'Archived')], default='staging', max_length=20)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_artifacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'stage'], name='idx_model_stage'), models.Index(fields=['created_at'], name='idx_model_created')],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
