predict_churn_task:
  description: >
    Analyze the provided customer CSV data to predict churn.
    The CSV data to analyze is: {csv_data}
    Expected columns: customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges.
    For example:
    Customer ID 123: Prediction = Churn (Raw: 1)
    Customer ID 456: Prediction = Not Churn (Raw: 0)
  expected_output: |
    A string containing the churn prediction results for each customer record in the input CSV.
    For example:
    Customer ID 123: Prediction = Churn (Raw: 1)
    Customer ID 456: Prediction = Not Churn (Raw: 0)
  agent: churn_predictor_agent
