# Generated by Django 5.2.1 on 2025-05-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_seeker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
