# Generated by Django 5.2.1 on 2025-05-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_seeker', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmcall',
            name='session',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='LlmCall',
        ),
    ]
